//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BookStore.DATA.ADO.NET
{
    using System;
    using System.Collections.Generic;
    
    public partial class BooksInStore
    {
        public int Id { get; set; }
        public int BookId { get; set; }
        public int StoreId { get; set; }
    
        public virtual Book Book { get; set; }
        public virtual Store Store { get; set; }
    }
}
